version: 1
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(message)s"
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./logs/sample.log
    maxBytes: 1000
    backupCount: 3
loggers:
  __main__:
    level: INFO
    handlers: [consoleHandler, fileHandler]
    propagate: no
root:
  level: INFO
  handlers: [consoleHandler, fileHandler]
